[package]
name = "dabus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flume = "0.10.12"
log = "0.4.16"
pretty_env_logger = "0.4.0"